# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/proto/schedules.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="models/proto/schedules.proto",
    package="schedule",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x1cmodels/proto/schedules.proto\x12\x08schedule"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05">\n\x10LocationSchedule\x12\x13\n\x0b\x64\x65partsCity\x18\x01 \x03(\t\x12\x15\n\rdepartsIsland\x18\x02 \x03(\t"\xd8\x01\n\x08Schedule\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x05start\x18\x02 \x01(\x0b\x32\x0e.schedule.Date\x12\x1b\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x0e.schedule.Date\x12\x34\n\tlocations\x18\x04 \x03(\x0b\x32!.schedule.Schedule.LocationsEntry\x1aL\n\x0eLocationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.schedule.LocationSchedule:\x02\x38\x01"2\n\tSchedules\x12%\n\tschedules\x18\x01 \x03(\x0b\x32\x12.schedule.Scheduleb\x06proto3'
    ),
)


_DATE = _descriptor.Descriptor(
    name="Date",
    full_name="schedule.Date",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="year",
            full_name="schedule.Date.year",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="month",
            full_name="schedule.Date.month",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="day",
            full_name="schedule.Date.day",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=42,
    serialized_end=90,
)


_LOCATIONSCHEDULE = _descriptor.Descriptor(
    name="LocationSchedule",
    full_name="schedule.LocationSchedule",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="departsCity",
            full_name="schedule.LocationSchedule.departsCity",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="departsIsland",
            full_name="schedule.LocationSchedule.departsIsland",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=92,
    serialized_end=154,
)


_SCHEDULE_LOCATIONSENTRY = _descriptor.Descriptor(
    name="LocationsEntry",
    full_name="schedule.Schedule.LocationsEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="schedule.Schedule.LocationsEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="schedule.Schedule.LocationsEntry.value",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=_b("8\001"),
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=297,
    serialized_end=373,
)

_SCHEDULE = _descriptor.Descriptor(
    name="Schedule",
    full_name="schedule.Schedule",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="schedule.Schedule.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="start",
            full_name="schedule.Schedule.start",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="end",
            full_name="schedule.Schedule.end",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="locations",
            full_name="schedule.Schedule.locations",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _SCHEDULE_LOCATIONSENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=157,
    serialized_end=373,
)


_SCHEDULES = _descriptor.Descriptor(
    name="Schedules",
    full_name="schedule.Schedules",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="schedules",
            full_name="schedule.Schedules.schedules",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=375,
    serialized_end=425,
)

_SCHEDULE_LOCATIONSENTRY.fields_by_name["value"].message_type = _LOCATIONSCHEDULE
_SCHEDULE_LOCATIONSENTRY.containing_type = _SCHEDULE
_SCHEDULE.fields_by_name["start"].message_type = _DATE
_SCHEDULE.fields_by_name["end"].message_type = _DATE
_SCHEDULE.fields_by_name["locations"].message_type = _SCHEDULE_LOCATIONSENTRY
_SCHEDULES.fields_by_name["schedules"].message_type = _SCHEDULE
DESCRIPTOR.message_types_by_name["Date"] = _DATE
DESCRIPTOR.message_types_by_name["LocationSchedule"] = _LOCATIONSCHEDULE
DESCRIPTOR.message_types_by_name["Schedule"] = _SCHEDULE
DESCRIPTOR.message_types_by_name["Schedules"] = _SCHEDULES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType(
    "Date",
    (_message.Message,),
    dict(
        DESCRIPTOR=_DATE,
        __module__="models.proto.schedules_pb2",
        # @@protoc_insertion_point(class_scope:schedule.Date)
    ),
)
_sym_db.RegisterMessage(Date)

LocationSchedule = _reflection.GeneratedProtocolMessageType(
    "LocationSchedule",
    (_message.Message,),
    dict(
        DESCRIPTOR=_LOCATIONSCHEDULE,
        __module__="models.proto.schedules_pb2",
        # @@protoc_insertion_point(class_scope:schedule.LocationSchedule)
    ),
)
_sym_db.RegisterMessage(LocationSchedule)

Schedule = _reflection.GeneratedProtocolMessageType(
    "Schedule",
    (_message.Message,),
    dict(
        LocationsEntry=_reflection.GeneratedProtocolMessageType(
            "LocationsEntry",
            (_message.Message,),
            dict(
                DESCRIPTOR=_SCHEDULE_LOCATIONSENTRY,
                __module__="models.proto.schedules_pb2",
                # @@protoc_insertion_point(class_scope:schedule.Schedule.LocationsEntry)
            ),
        ),
        DESCRIPTOR=_SCHEDULE,
        __module__="models.proto.schedules_pb2",
        # @@protoc_insertion_point(class_scope:schedule.Schedule)
    ),
)
_sym_db.RegisterMessage(Schedule)
_sym_db.RegisterMessage(Schedule.LocationsEntry)

Schedules = _reflection.GeneratedProtocolMessageType(
    "Schedules",
    (_message.Message,),
    dict(
        DESCRIPTOR=_SCHEDULES,
        __module__="models.proto.schedules_pb2",
        # @@protoc_insertion_point(class_scope:schedule.Schedules)
    ),
)
_sym_db.RegisterMessage(Schedules)


_SCHEDULE_LOCATIONSENTRY._options = None
# @@protoc_insertion_point(module_scope)
