# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models/proto/schedules.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'models/proto/schedules.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmodels/proto/schedules.proto\x12\x08schedule\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\">\n\x10LocationSchedule\x12\x13\n\x0b\x64\x65partsCity\x18\x01 \x03(\t\x12\x15\n\rdepartsIsland\x18\x02 \x03(\t\"\xd8\x01\n\x08Schedule\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x05start\x18\x02 \x01(\x0b\x32\x0e.schedule.Date\x12\x1b\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x0e.schedule.Date\x12\x34\n\tlocations\x18\x04 \x03(\x0b\x32!.schedule.Schedule.LocationsEntry\x1aL\n\x0eLocationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.schedule.LocationSchedule:\x02\x38\x01\"2\n\tSchedules\x12%\n\tschedules\x18\x01 \x03(\x0b\x32\x12.schedule.Scheduleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.proto.schedules_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULE_LOCATIONSENTRY']._loaded_options = None
  _globals['_SCHEDULE_LOCATIONSENTRY']._serialized_options = b'8\001'
  _globals['_DATE']._serialized_start=42
  _globals['_DATE']._serialized_end=90
  _globals['_LOCATIONSCHEDULE']._serialized_start=92
  _globals['_LOCATIONSCHEDULE']._serialized_end=154
  _globals['_SCHEDULE']._serialized_start=157
  _globals['_SCHEDULE']._serialized_end=373
  _globals['_SCHEDULE_LOCATIONSENTRY']._serialized_start=297
  _globals['_SCHEDULE_LOCATIONSENTRY']._serialized_end=373
  _globals['_SCHEDULES']._serialized_start=375
  _globals['_SCHEDULES']._serialized_end=425
# @@protoc_insertion_point(module_scope)
