name: Download and Push File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run at UTC midnight every day

jobs:
  generate_schedule_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout island-ferry-tracker
        uses: actions/checkout@v4
        with:
          repository: 'RamVasuthevan/island-ferry-tracker'
          ref: ${{ github.event_name == 'workflow_dispatch' && github.ref || 'main' }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run json_schedule_generator.py
        working-directory: src/json-schedule-generator
        run: |
          pip install pipenv
          pipenv install
          pipenv run python json_schedule_generator.py

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Check for changes in output files
        id: check_changes
        run: |
          git diff --exit-code output/schedule.json output/schedule.html && \
          (echo "No changes detected in output files" && echo "changes=no" >> $GITHUB_ENV) || \
          (echo "Changes detected in output files" && echo "changes=yes" >> $GITHUB_ENV)
        
      - name: Create Pull Request
        if: env.changes == 'yes'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Automatically updated on ${{ steps.date.outputs.date }}"
          title: "Update schedules files - ${{ steps.date.outputs.date }}"
          branch: "update-schedules-files-${{ steps.date.outputs.date }}-${{ github.run_number }}"
          labels: automated-pr
  
      - name: PR details
        if: env.changes == 'yes'
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
