name: Pre-commit

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_generate_schedule_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout island-ferry-tracker
        uses: actions/checkout@v4
        with:
          repository: 'RamVasuthevan/island-ferry-tracker'
          ref: ${{ github.event_name == 'workflow_dispatch' && github.ref || 'main' }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install protobuf
        run: sudo apt-get install -y protobuf-compiler

      - name: Generate protobuf files
        working-directory: src/json-schedule-generator
        run: protoc -I=models/proto --python_out=models/proto models/proto/schedules.proto

      - name: Run json_schedule_generator.py
        working-directory: src/json-schedule-generator
        run: |
          pip install pipenv
          pipenv install
          pipenv run python json_schedule_generator.py
